hash1: hash1.c
	gcc -o hash1 hash1.c -I`brew --prefix openssl`/include -L`brew --prefix openssl`/lib -lssl -lcrypto

hash2: hash2.c
	gcc -o hash2 hash2.c -I`brew --prefix openssl`/include -L`brew --prefix openssl`/lib -lssl -lcrypto